### ISSUE TITLE
Cannot download the dataset

### ISSUE THREAD

**Issue by haochengxi** [Anima-Lab/MaskDiT#15]
Thanks for this wonderful repo!
However, I can not download the dataset by running bash scripts/download_assets.sh.
The error is as follows:
> Start downloading...
> Traceback (most recent call last):
>   File "download_assets.py", line 61, in <module>
>     main(args)
>   File "download_assets.py", line 49, in main
>     download_file(url + file_name, file_path)
>   File "download_assets.py", line 29, in download_file
>     r.raise_for_status()
>   File "/root/miniconda3/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://slurm-ord.s3.amazonaws.com/datasets/imagenet_256_latent_lmdb/train/data.mdb

Could you please try to solve this issue? Thanks!

**Comment by devzhk** [comment]
Please see #13 for updated links.
